#!/bin/bash 
echo Griffin software beta version 0.1.5

split_prefix="~griffin-split-"
batch_size=1000

echo splitting [$1]...
split -l $batch_size $1 $split_prefix

basinsfile=( $(cat $GRIFFIN_HOME/conf/griffin.properties | grep "app.option.basins.out.file" | tr "=" "\n") )

for filename in $(ls ${split_prefix}*);do
  echo -n "."
  java $GRIFFIN_JVM_OPTIONS -Dlog4j.configuration=file:$GRIFFIN_HOME/conf/log4j.properties -classpath .:$GRIFFIN_HOME/conf:$GRIFFIN_HOME/lib/commons-beanutils-1.8.3.jar:$GRIFFIN_HOME/lib/commons-beanutils-bean-collections-1.8.3.jar:$GRIFFIN_HOME/lib/commons-beanutils-core-1.8.3.jar:$GRIFFIN_HOME/lib/commons-cli-1.3.1.jar:$GRIFFIN_HOME/lib/commons-lang3-3.1.jar:$GRIFFIN_HOME/lib/log4j-1.2.17.jar:$GRIFFIN_HOME/lib/org.sat4j.core.jar:$GRIFFIN_HOME/lib/beedeedee.jar:$GRIFFIN_HOME/lib/julia-annotations-1.9.20.jar:$GRIFFIN_HOME/lib/mockito-all-1.9.5.jar:$GRIFFIN_HOME/bin/griffin0.1.5.jar mx.unam.iimas.griffin.grn.explorer.Basins "$filename"
  mv "${basinsfile[1]}" "$filename"
done

echo joining [$basinsfile[1]]
cat ${split_prefix}* > "${basinsfile[1]}"
rm ${split_prefix}*




